name: Release build

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      ANDROID_SDK_TOOLS:    "4333796"
      ANDROID_COMPILE_SDK:  "29"
      ANDROID_BUILD_TOOLS:  "29.0.2"
      ANDROID_NDK:          "20.0.5594570"
      ANDROID_CMAKE:        "3.10.2.4988404"
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Android sdkmanager
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
        sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null
        rm android-sdk.zip

    - name: Install required Android tools
      run: |
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" > /dev/null
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" > /dev/null
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "cmake;${ANDROID_CMAKE}" > /dev/null
        echo ::set-env PATH="$ANDROID_HOME/cmake/$ANDROID_CMAKE/bin:$PATH"
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;${ANDROID_NDK}" > /dev/null
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null

    - name: Build dependencies
      run: ./dobuilddependencies --serial --cleanup

    - name: Build main library
      run: ./gradlew assembleRelease

    - name: Upload to Bintray
      run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_API_USER }} -PbintrayApiKey=${{ secrets.BINTRAY_API_KEY }}
