name: Build
on: push

env:
  ANDROID_SDK_TOOLS:  "4333796"
  ANDROID_NDK:        "20.1.5948944"
  ANDROID_CMAKE:      "3.10.2.4988404"

jobs:
  debug:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        abi: [ x86, x86_64, armeabi-v7a, arm64-v8a ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache android-sdk.zip
        uses: actions/cache@v1
        with:
          key: android-sdk.zip-${{ env.ANDROID_SDK_TOOLS }}
          path: android-sdk.zip

      - run: .github/installAndroidTools.sh

      - run: .github/installBuildDependencies.sh

      - name: Cache tarballs
        uses: actions/cache@v1
        with:
          key: tarballs
          path: dependency-builder/src/main/cpp/tarballs

      - run: ./dodownloadtarballs

      - name: Build pdf2htmlEX
        run: ./gradlew assembleDebug -PdisablePreDex -Pabi=${{ matrix.abi }}

      - name: Upload build logs -stdout
        uses: actions/upload-artifact@v1
        with:
          name: debug-${{ matrix.abi }}-dependency-builder.stdout
          path: pdf2htmlEX/.cxx/cmake/debug/${{ matrix.abi }}/dependency-builder.stdout

      - name: Upload build logs -stderr
        uses: actions/upload-artifact@v1
        with:
          name: debug-${{ matrix.abi }}-dependency-builder.stderr
          path: pdf2htmlEX/.cxx/cmake/debug/${{ matrix.abi }}/dependency-builder.stderr

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        abi: [ x86, x86_64, armeabi-v7a, arm64-v8a ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache android-sdk.zip
        uses: actions/cache@v1
        with:
          key: android-sdk.zip-${{ env.ANDROID_SDK_TOOLS }}
          path: android-sdk.zip

      - run: .github/installAndroidTools.sh

      - run: .github/installBuildDependencies.sh

      - name: Cache tarballs
        uses: actions/cache@v1
        with:
          key: tarballs
          path: dependency-builder/src/main/cpp/tarballs

      - run: ./dodownloadtarballs

      - name: Build pdf2htmlEX-Android dependencies
        run: ./gradlew dependency-builder:assembleRelease -PdisablePreDex -Pabi=${{ matrix.abi }}

      - name: Gather licenses
        run: ./gradlew pdf2htmlEX:gatherLicenses -Pabi=${{ matrix.abi }}

      - name: Artifact gathered licenses
        uses: actions/upload-artifact@v1
        with:
          name: licenses-${{ matrix.abi }}
          path: pdf2htmlEX/build/licenses.xml

      - name: Artifact built dependencies
        uses: actions/upload-artifact@v1
        with:
          name: dependencies-${{ matrix.abi }}
          path: dependency-builder/.cxx/cmake/release/${{ matrix.abi }}/installed

      - name: Upload build logs -stdout
        uses: actions/upload-artifact@v1
        with:
          name: release-${{ matrix.abi }}-dependency-builder.stdout
          path: pdf2htmlEX/.cxx/cmake/release/${{ matrix.abi }}/dependency-builder.stdout

      - name: Upload build logs -stderr
        uses: actions/upload-artifact@v1
        with:
          name: release-${{ matrix.abi }}-dependency-builder.stderr
          path: pdf2htmlEX/.cxx/cmake/release/${{ matrix.abi }}/dependency-builder.stderr

  releaseAllABIs:
    needs: release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache android-sdk.zip
        uses: actions/cache@v1
        with:
          key: android-sdk.zip-${{ env.ANDROID_SDK_TOOLS }}
          path: android-sdk.zip

      - run: .github/installAndroidTools.sh

      - name: Download artifacted licenses
        uses: actions/download-artifact@v1
        with:
          name: licenses-x86
          path: pdf2htmlEX/build/licenses.xml

      - name: Download artifacted dependencies - x86
        uses: actions/download-artifact@v1
        with:
          name: dependencies-x86
          path: dependency-builder/.cxx/cmake/release/x86/installed

      - name: Download artifacted dependencies - x86_64
        uses: actions/download-artifact@v1
        with:
          name: dependencies-x86_64
          path: dependency-builder/.cxx/cmake/release/x86_64/installed

      - name: Download artifacted dependencies - armeabi-v7a
        uses: actions/download-artifact@v1
        with:
          name: dependencies-armeabi-v7a
          path: dependency-builder/.cxx/cmake/release/armeabi-v7a/installed

      - name: Download artifacted dependencies - arm64-v8a
        uses: actions/download-artifact@v1
        with:
          name: dependencies-arm64-v8a
          path: dependency-builder/.cxx/cmake/release/arm64-v8a/installed

      - name: Build pdf2htmlEX-Android
        run: ./gradlew assembleRelease -PdisablePreDex

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(./getVersion.sh)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: pdf2htmlEX-Android v${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false

      - name: Upload licenses
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pdf2htmlEX/build/licenses.xml
          asset_name: licenses.xml
          asset_content_type: text/xml

      - name: Upload aar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pdf2htmlEX/build/outputs/aar/pdf2htmlex-android-release.aar
          asset_name: pdf2htmlex-android-release.aar
          asset_content_type: application/zip

      - name: Generate javadoc
        run: ./gradlew pdf2htmlEX:javadocJar

      - name: Upload javadoc.jar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pdf2htmlEX/build/libs/pdf2htmlex-android-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_name: pdf2htmlex-android-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_content_type: application/zip

      - name: Jar the sources
        run: ./gradlew pdf2htmlEX:sourceJar

      - name: Upload sources.jar
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pdf2htmlEX/build/libs/pdf2htmlex-android-${{steps.get_version.outputs.version}}-sources.jar
          asset_name: pdf2htmlex-android-${{steps.get_version.outputs.version}}-sources.jar
          asset_content_type: application/zip
