name: Release Publisher

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Download assets from this Release
        uses: ViliusSutkus89/release-asset-downloader@v1.0.2
        with:
          outputDirectory: 'releaseAssets'

      - name: Put release assets where gradle would have kept it after the build
        run: |
          mkdir --parents ./pdf2htmlEX/build/outputs/aar
          cp ./releaseAssets/pdf2htmlex-android-release.aar $BASEDIR/pdf2htmlEX/build/outputs/aar/

          mkdir --parents ./pdf2htmlEX/build/libs
          cp ./releaseAssets/pdf2htmlex-android-*-javadoc.jar ./pdf2htmlEX/build/libs/
          cp ./releaseAssets/pdf2htmlex-android-*-sources.jar ./pdf2htmlEX/build/libs/

          mv ./releaseAssets/licenses.xml ./pdf2htmlEX/build/

      - name: Upload to Bintray
        run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_API_USER }} -PbintrayApiKey=${{ secrets.BINTRAY_API_KEY }}

